// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2vuBJ1e3y4yYidzmU-uq8nV-zVf150_U',
    appId: '1:626366007732:web:8a82d69afcba96a7a30ae1',
    messagingSenderId: '626366007732',
    projectId: 'clothed-9c179',
    authDomain: 'clothed-9c179.firebaseapp.com',
    storageBucket: 'clothed-9c179.appspot.com',
    measurementId: 'G-ZMHRP4JHTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVKXlx4zm9XDYgBL7VrAA_XUHktFdxP6Q',
    appId: '1:626366007732:android:904aa4b9f5bd645aa30ae1',
    messagingSenderId: '626366007732',
    projectId: 'clothed-9c179',
    storageBucket: 'clothed-9c179.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAomdhOtn_pgxA1idlJ7ATdQMz55GD2ILA',
    appId: '1:626366007732:ios:d68614b4375ed74ca30ae1',
    messagingSenderId: '626366007732',
    projectId: 'clothed-9c179',
    storageBucket: 'clothed-9c179.appspot.com',
    iosBundleId: 'com.clothed.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAomdhOtn_pgxA1idlJ7ATdQMz55GD2ILA',
    appId: '1:626366007732:ios:d68614b4375ed74ca30ae1',
    messagingSenderId: '626366007732',
    projectId: 'clothed-9c179',
    storageBucket: 'clothed-9c179.appspot.com',
    iosBundleId: 'com.clothed.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2vuBJ1e3y4yYidzmU-uq8nV-zVf150_U',
    appId: '1:626366007732:web:377c55746e27bba4a30ae1',
    messagingSenderId: '626366007732',
    projectId: 'clothed-9c179',
    authDomain: 'clothed-9c179.firebaseapp.com',
    storageBucket: 'clothed-9c179.appspot.com',
    measurementId: 'G-15XM1EX2F5',
  );
}
